language: csharp
solution: src/SoundFingerprinting.Solr.sln
dotnet: 2.1.300
services:
  - docker
before_install:
  - docker pull addictedcs/soundfingerprinting.solr
  - docker run -d -p 8983:8983 addictedcs/soundfingerprinting.solr
install:
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory build/testrunner
script:
  - dotnet restore ./src/SoundFingerprinting.Solr.sln
  - dotnet build ./src/SounFingerprinting.Solr.Tests/SoundFingerprinting.Solr.Tests.csproj -c Release -f netcoreapp2.1
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/846dee77235fe9abbb02
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always